FROM wordpress:6.0.2-php8.0-fpm

# Install sockets for PHP
RUN docker-php-ext-install sockets

# Install wp-cli
# RUN curl -O -L https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN curl "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar" --output "/var/wp-cli.phar"
RUN php /var/wp-cli.phar --info
RUN chmod +x /var/wp-cli.phar
RUN mv /var/wp-cli.phar /usr/local/bin/wp